site_name: infosecintelDocs

nav:
  - Home: index.md
  - About: about.md
  - "Website Configs": webpage-configs.md

theme:
  name: readthedocs
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:

  # Python Markdown Extensions

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
